services:
  - type: web
    name: physforge
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: KMP_DUPLICATE_LIB_OK
        value: TRUE
      - key: PYTHON_VERSION
        value: 3.11.9
