services:
  - type: web
    name: physforge
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: KMP_DUPLICATE_LIB_OK
        value: TRUE
